default: &default
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_react_development
  username: postgres
  password: reg.edit123

test:
  <<: *default
  database: rails_react_test

production:
  <<: *default
  database: hello_rails_react_production
